<a href="https://colab.research.google.com/github/nikrod/MagisterIA/blob/master/cuda%20y%20tensores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
#device = torch.cuda.current_device()
cuda0 = torch.device('cuda:0')

A = [[1,2,3], [4,5,6], [7,8,9]]
B = [[10,11,12], [13,14,15], [16,17,18]]
tensorA = torch.tensor(A, device=cuda0).type(torch.float)
tensorB = torch.tensor(B, device=cuda0).type(torch.float)
print(tensorA)
print(tensorB)

z = torch.matmul(tensorA,tensorB)
print(z)



tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], device='cuda:0')
tensor([[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]], device='cuda:0')
tensor([[ 84.,  90.,  96.],
        [201., 216., 231.],
        [318., 342., 366.]], device='cuda:0')
